spring.application.name=code_Practice21

spring.datasource.url=jdbc:postgresql://localhost:5432/data_practise3
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true